name: test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['12']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Test 1
        run: echo "$(git --no-pager shortlog -nes -- ./.github/workflows/test.yml)"

      - name: Test 2
        run: echo "$(git --no-pager shortlog -nes HEAD -- ./.github/workflows/test.yml)"
